# This is a basic workflow that is manually triggered

name: List all MD files

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Runs a single command using the runners shell
    # - name: LS  
    #   run: ls $GITHUB_WORKSPACE
      
    - name: Geef lijst met MD files
      run: mkdir ./public && cd $GITHUB_WORKSPACE && find * -type d -name node_modules -prune -o -name '*.md' -print > ./public/content.txt

    - name: List folders
      run: ls -a
    
    - name: Kopieer alle .md files naar public folder
      run: find * -name "*.md" -exec cp --parents "{}" "./public/"  \;
      
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public/
